apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-authentications-secret
type: Opaque
stringData:
  authentications.json: |-
    {
      "amqp": {
        "broker": "rabbitmq.default.svc.cluster.local",
        "username": "dripline",
        "password": "dripline"
      },
        "postgresql": {
          "username": "dripline",
          "password": "dripline"
      }
    }
